name: myappflutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/bake.jpg
    - img/macarons.jpg
    - img/ice-cream.jpg
    - img/baby-snow-leopard.jpg
    - img/black-cat.jpg
    - img/cat.jpg
    - img/kittens.jpg
    - img/pug.jpg
    - img/black-panter.png
    

